In [1]:
import pandas as pd

data = {
    "Loan_ID": [
        1001, 1002, 1003, 1004, 1005,
        1006, 1007, 1008, 1009, 1010,
        1011, 1012, 1013, 1014, 1015,
        1016, 1017, 1018, 1019, 1020,
        1021, 1022, 1023, 1024, 1025,
        1026, 1027, 1028, 1029, 1030
    ],

    "Customer_Name": [
        "Arshad", "Rahul", "Priya", "Kiran", "Anjali",
        "Vikram", "Sneha", "Ravi", "Neha", "Aman",
        "Suresh", "Divya", "Naveen", "Pooja", "Imran",
        "Kavya", "Rohit", "Meena", "Adil", "Swathi",
        "Manoj", "Ayesha", "Tarun", "Lakshmi", "Farhan",
        "Deepak", "Nisha", "Varun", "Shreya", "Akash"
    ],

    "Age": [
        24, 29, 35, 42, 31,
        27, 39, 45, 26, 33,
        38, 30, 41, 28, 36,
        25, 44, 32, 37, 40,
        29, 34, 46, 27, 39,
        31, 43, 28, 36, 41
    ],

    "Gender": [
        "Male", "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male",
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male",
        "Male", "Female", "Male", "Female", "Male"
    ],

    "Region": [
        "South", "South", "West", "North", "South",
        "East", "South", "West", "South", "North",
        "East", "South", "North", "West", "South",
        "East", "North", "South", "West", "South",
        "North", "South", "East", "West", "South",
        "North", "South", "West", "East", "South"
    ],

    "Employment_Type": [
        "Salaried", "Self-Employed", "Salaried", "Salaried", "Self-Employed",
        "Salaried", "Salaried", "Self-Employed", "Salaried", "Salaried",
        "Self-Employed", "Salaried", "Salaried", "Self-Employed", "Salaried",
        "Salaried", "Self-Employed", "Salaried", "Salaried", "Self-Employed",
        "Salaried", "Salaried", "Self-Employed", "Salaried", "Salaried",
        "Self-Employed", "Salaried", "Salaried", "Self-Employed", "Salaried"
    ],

    "Annual_Income": [
        450000, 650000, 800000, 950000, 550000,
        720000, 880000, 1100000, 480000, 600000,
        750000, 520000, 900000, 680000, 820000,
        470000, 1050000, 580000, 760000, 630000,
        700000, 850000, 1150000, 490000, 780000,
        620000, 920000, 540000, 730000, 980000
    ],

    "Loan_Amount": [
        200000, 350000, 500000, 750000, 300000,
        400000, 600000, 900000, 250000, 450000,
        550000, 280000, 700000, 380000, 650000,
        220000, 800000, 320000, 500000, 420000,
        360000, 580000, 950000, 240000, 620000,
        310000, 720000, 290000, 470000, 680000
    ],

    "Interest_Rate": [
        8.5, 9.2, 7.8, 8.1, 10.5,
        9.0, 8.2, 7.5, 11.0, 9.5,
        8.0, 10.2, 7.9, 9.1, 8.4,
        11.5, 7.6, 10.0, 8.7, 9.3,
        8.9, 8.1, 7.4, 10.8, 8.6,
        9.7, 7.8, 10.4, 8.8, 8.0
    ],

    "Loan_Term_Years": [
        5, 7, 10, 15, 5,
        7, 10, 15, 5, 7,
        10, 5, 15, 7, 10,
        5, 15, 7, 10, 7,
        5, 10, 15, 5, 10,
        7, 15, 5, 10, 15
    ],

    "Credit_Score": [
        760, 720, 810, 780, 650,
        735, 790, 820, 620, 700,
        775, 660, 805, 710, 750,
        590, 815, 680, 745, 690,
        725, 795, 610, 640, 770,
        685, 800, 625, 755, 815
    ],

    "DTI_Ratio": [
        18, 25, 15, 20, 38,
        22, 17, 12, 45, 30,
        19, 40, 14, 28, 21,
        52, 13, 35, 23, 32,
        24, 16, 48, 42, 20,
        34, 15, 39, 22, 18
    ],

    "Loan_Purpose": [
        "Home", "Education", "Home", "Business", "Personal",
        "Vehicle", "Home", "Business", "Personal", "Education",
        "Home", "Personal", "Business", "Vehicle", "Home",
        "Personal", "Business", "Education", "Vehicle", "Home",
        "Vehicle", "Home", "Business", "Personal", "Education",
        "Home", "Business", "Personal", "Vehicle", "Home"
    ],

    "Application_Status": [
        "Approved", "Approved", "Approved", "Approved", "Approved",
        "Approved", "Approved", "Approved", "Rejected", "Approved",
        "Approved", "Rejected", "Approved", "Approved", "Approved",
        "Rejected", "Approved", "Rejected", "Approved", "Approved",
        "Approved", "Approved", "Rejected", "Rejected", "Approved",
        "Approved", "Approved", "Rejected", "Approved", "Approved"
    ],

    "Repayment_Status": [
        "Paid", "Paid", "Paid", "Paid", "Late",
        "Paid", "Paid", "Paid", "Default", "Paid",
        "Paid", "Default", "Paid", "Late", "Paid",
        "Default", "Paid", "Default", "Paid", "Late",
        "Paid", "Paid", "Default", "Default", "Paid",
        "Paid", "Paid", "Default", "Paid", "Paid"
    ]
}

df = pd.DataFrame(data)

print("Bank Loan Dataset Created Successfully!")
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

df

Bank Loan Dataset Created Successfully!
Number of rows: 30
Number of columns: 15

,Loan_ID,Customer_Name,Age,Gender,Region,Employment_Type,Annual_Income,Loan_Amount,Interest_Rate,Loan_Term_Years,Credit_Score,DTI_Ratio,Loan_Purpose,Application_Status,Repayment_Status
0,1001,Arshad,24,Male,South,Salaried,450000,200000,8.5,5,760,18,Home,Approved,Paid
1,1002,Rahul,29,Male,South,Self-Employed,650000,350000,9.2,7,720,25,Education,Approved,Paid
2,1003,Priya,35,Female,West,Salaried,800000,500000,7.8,10,810,15,Home,Approved,Paid
3,1004,Kiran,42,Male,North,Salaried,950000,750000,8.1,15,780,20,Business,Approved,Paid
4,1005,Anjali,31,Female,South,Self-Employed,550000,300000,10.5,5,650,38,Personal,Approved,Late
5,1006,Vikram,27,Male,East,Salaried,720000,400000,9.0,7,735,22,Vehicle,Approved,Paid
6,1007,Sneha,39,Female,South,Salaried,880000,600000,8.2,10,790,17,Home,Approved,Paid
7,1008,Ravi,45,Male,West,Self-Employed,1100000,900000,7.5,15,820,12,Business,Approved,Paid
8,1009,Neha,26,Female,South,Salaried,480000,250000,11.0,5,620,45,Personal,Rejected,Default
9,1010,Aman,33,Male,North,Salaried,600000,450000,9.5,7,700,30,Education,Approved,Paid
10,1011,Suresh,38,Male,East,Self-Employed,750000,550000,8.0,10,775,19,Home,Approved,Paid
11,1012,Divya,30,Female,South,Salaried,520000,280000,10.2,5,660,40,Personal,Rejected,Default
12,1013,Naveen,41,Male,North,Salaried,900000,700000,7.9,15,805,14,Business,Approved,Paid
13,1014,Pooja,28,Female,West,Self-Employed,680000,380000,9.1,7,710,28,Vehicle,Approved,Late
14,1015,Imran,36,Male,South,Salaried,820000,650000,8.4,10,750,21,Home,Approved,Paid
15,1016,Kavya,25,Female,East,Salaried,470000,220000,11.5,5,590,52,Personal,Rejected,Default
16,1017,Rohit,44,Male,North,Self-Employed,1050000,800000,7.6,15,815,13,Business,Approved,Paid
17,1018,Meena,32,Female,South,Salaried,580000,320000,10.0,7,680,35,Education,Rejected,Default
18,1019,Adil,37,Male,West,Salaried,760000,500000,8.7,10,745,23,Vehicle,Approved,Paid
19,1020,Swathi,40,Female,South,Self-Employed,630000,420000,9.3,7,690,32,Home,Approved,Late
20,1021,Manoj,29,Male,North,Salaried,700000,360000,8.9,5,725,24,Vehicle,Approved,Paid
21,1022,Ayesha,34,Female,South,Salaried,850000,580000,8.1,10,795,16,Home,Approved,Paid
22,1023,Tarun,46,Male,East,Self-Employed,1150000,950000,7.4,15,610,48,Business,Rejected,Default
23,1024,Lakshmi,27,Female,West,Salaried,490000,240000,10.8,5,640,42,Personal,Rejected,Default
24,1025,Farhan,39,Male,South,Salaried,780000,620000,8.6,10,770,20,Education,Approved,Paid
25,1026,Deepak,31,Male,North,Self-Employed,620000,310000,9.7,7,685,34,Home,Approved,Paid
26,1027,Nisha,43,Female,South,Salaried,920000,720000,7.8,15,800,15,Business,Approved,Paid
27,1028,Varun,28,Male,West,Salaried,540000,290000,10.4,5,625,39,Personal,Rejected,Default
28,1029,Shreya,36,Female,East,Self-Employed,730000,470000,8.8,10,755,22,Vehicle,Approved,Paid
29,1030,Akash,41,Male,South,Salaried,980000,680000,8.0,15,815,18,Home,Approved,Paid

In [2]:
print("BANK LOAN DATASET CHECK")
print("=======================")

print("\nFirst 5 Records:")
print(df.head())

print("\nLast 5 Records:")
print(df.tail())

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nMissing Values:")
print(df.isnull().sum())

BANK LOAN DATASET CHECK
=======================

First 5 Records:
   Loan_ID Customer_Name  Age  Gender Region Employment_Type  Annual_Income  \
0     1001        Arshad   24    Male  South        Salaried         450000
1     1002         Rahul   29    Male  South   Self-Employed         650000
2     1003         Priya   35  Female   West        Salaried         800000
3     1004         Kiran   42    Male  North        Salaried         950000
4     1005        Anjali   31  Female  South   Self-Employed         550000

   Loan_Amount  Interest_Rate  Loan_Term_Years  Credit_Score  DTI_Ratio  \
0       200000            8.5                5           760         18
1       350000            9.2                7           720         25
2       500000            7.8               10           810         15
3       750000            8.1               15           780         20
4       300000           10.5                5           650         38

  Loan_Purpose Application_Status Repayment_Status
0         Home           Approved             Paid
1    Education           Approved             Paid
2         Home           Approved             Paid
3     Business           Approved             Paid
4     Personal           Approved             Late

Last 5 Records:
    Loan_ID Customer_Name  Age  Gender Region Employment_Type  Annual_Income  \
25     1026        Deepak   31    Male  North   Self-Employed         620000
26     1027         Nisha   43  Female  South        Salaried         920000
27     1028         Varun   28    Male   West        Salaried         540000
28     1029        Shreya   36  Female   East   Self-Employed         730000
29     1030         Akash   41    Male  South        Salaried         980000

    Loan_Amount  Interest_Rate  Loan_Term_Years  Credit_Score  DTI_Ratio  \
25       310000            9.7                7           685         34
26       720000            7.8               15           800         15
27       290000           10.4                5           625         39
28       470000            8.8               10           755         22
29       680000            8.0               15           815         18

   Loan_Purpose Application_Status Repayment_Status
25         Home           Approved             Paid
26     Business           Approved             Paid
27     Personal           Rejected          Default
28      Vehicle           Approved             Paid
29         Home           Approved             Paid

Dataset Shape:
(30, 15)

Column Names:
['Loan_ID', 'Customer_Name', 'Age', 'Gender', 'Region', 'Employment_Type', 'Annual_Income', 'Loan_Amount', 'Interest_Rate', 'Loan_Term_Years', 'Credit_Score', 'DTI_Ratio', 'Loan_Purpose', 'Application_Status', 'Repayment_Status']

Missing Values:
Loan_ID               0
Customer_Name         0
Age                   0
Gender                0
Region                0
Employment_Type       0
Annual_Income         0
Loan_Amount           0
Interest_Rate         0
Loan_Term_Years       0
Credit_Score          0
DTI_Ratio             0
Loan_Purpose          0
Application_Status    0
Repayment_Status      0
dtype: int64

In [3]:
# Add application dates

df["Application_Date"] = pd.to_datetime([
    "2025-01-05", "2025-01-12", "2025-01-20", "2025-02-03", "2025-02-15",
    "2025-02-25", "2025-03-08", "2025-03-18", "2025-03-28", "2025-04-06",
    "2025-04-15", "2025-04-25", "2025-05-05", "2025-05-16", "2025-05-27",
    "2025-06-07", "2025-06-18", "2025-06-29", "2025-07-08", "2025-07-20",
    "2025-07-30", "2025-08-10", "2025-08-21", "2025-08-31", "2025-09-10",
    "2025-09-20", "2025-09-30", "2025-10-10", "2025-10-20", "2025-10-30"
])

print("Application dates added successfully!")
print(df[["Loan_ID", "Customer_Name", "Application_Date"]].head(10))

Application dates added successfully!
   Loan_ID Customer_Name Application_Date
0     1001        Arshad       2025-01-05
1     1002         Rahul       2025-01-12
2     1003         Priya       2025-01-20
3     1004         Kiran       2025-02-03
4     1005        Anjali       2025-02-15
5     1006        Vikram       2025-02-25
6     1007         Sneha       2025-03-08
7     1008          Ravi       2025-03-18
8     1009          Neha       2025-03-28
9     1010          Aman       2025-04-06

In [4]:
# Calculate Funded Amount

df["Funded_Amount"] = df.apply(
    lambda row: row["Loan_Amount"]
    if row["Application_Status"] == "Approved"
    else 0,
    axis=1
)

# Calculate Received Amount
df["Received_Amount"] = df.apply(
    lambda row: (
        row["Loan_Amount"] * 1.10
        if row["Repayment_Status"] == "Paid"
        else row["Loan_Amount"] * 0.90
        if row["Repayment_Status"] == "Late"
        else row["Loan_Amount"] * 0.40
        if row["Repayment_Status"] == "Default"
        else 0
    ),
    axis=1
)

print("Funded and Received Amounts Created!")
print()

print(
    df[
        [
            "Loan_ID",
            "Loan_Amount",
            "Application_Status",
            "Repayment_Status",
            "Funded_Amount",
            "Received_Amount"
        ]
    ].head(10)
)

Funded and Received Amounts Created!

   Loan_ID  Loan_Amount Application_Status Repayment_Status  Funded_Amount  \
0     1001       200000           Approved             Paid         200000
1     1002       350000           Approved             Paid         350000
2     1003       500000           Approved             Paid         500000
3     1004       750000           Approved             Paid         750000
4     1005       300000           Approved             Late         300000
5     1006       400000           Approved             Paid         400000
6     1007       600000           Approved             Paid         600000
7     1008       900000           Approved             Paid         900000
8     1009       250000           Rejected          Default              0
9     1010       450000           Approved             Paid         450000

   Received_Amount
0         220000.0
1         385000.0
2         550000.0
3         825000.0
4         270000.0
5         440000.0
6         660000.0
7         990000.0
8         100000.0
9         495000.0

In [5]:
# Calculate Funded Amount

df["Funded_Amount"] = df.apply(
    lambda row: row["Loan_Amount"]
    if row["Application_Status"] == "Approved"
    else 0,
    axis=1
)

# Calculate Received Amount
df["Received_Amount"] = df.apply(
    lambda row: (
        row["Loan_Amount"] * 1.10
        if row["Repayment_Status"] == "Paid"
        else row["Loan_Amount"] * 0.90
        if row["Repayment_Status"] == "Late"
        else row["Loan_Amount"] * 0.40
        if row["Repayment_Status"] == "Default"
        else 0
    ),
    axis=1
)

print("Funded and Received Amounts Created!")
print()

print(
    df[
        [
            "Loan_ID",
            "Loan_Amount",
            "Application_Status",
            "Repayment_Status",
            "Funded_Amount",
            "Received_Amount"
        ]
    ].head(10)
)

Funded and Received Amounts Created!

   Loan_ID  Loan_Amount Application_Status Repayment_Status  Funded_Amount  \
0     1001       200000           Approved             Paid         200000
1     1002       350000           Approved             Paid         350000
2     1003       500000           Approved             Paid         500000
3     1004       750000           Approved             Paid         750000
4     1005       300000           Approved             Late         300000
5     1006       400000           Approved             Paid         400000
6     1007       600000           Approved             Paid         600000
7     1008       900000           Approved             Paid         900000
8     1009       250000           Rejected          Default              0
9     1010       450000           Approved             Paid         450000

   Received_Amount
0         220000.0
1         385000.0
2         550000.0
3         825000.0
4         270000.0
5         440000.0
6         660000.0
7         990000.0
8         100000.0
9         495000.0

In [6]:
# Classify loans into Good, Bad, and Rejected

df["Loan_Quality"] = df.apply(
    lambda row: "Good Loan"
    if row["Application_Status"] == "Approved"
    and row["Repayment_Status"] == "Paid"
    else "Bad Loan"
    if row["Application_Status"] == "Approved"
    and row["Repayment_Status"] in ["Late", "Default"]
    else "Rejected",
    axis=1
)

print("Loan classification completed!")
print()

print(
    df[
        [
            "Loan_ID",
            "Customer_Name",
            "Application_Status",
            "Repayment_Status",
            "Loan_Quality"
        ]
    ]
)

Loan classification completed!

    Loan_ID Customer_Name Application_Status Repayment_Status Loan_Quality
0      1001        Arshad           Approved             Paid    Good Loan
1      1002         Rahul           Approved             Paid    Good Loan
2      1003         Priya           Approved             Paid    Good Loan
3      1004         Kiran           Approved             Paid    Good Loan
4      1005        Anjali           Approved             Late     Bad Loan
5      1006        Vikram           Approved             Paid    Good Loan
6      1007         Sneha           Approved             Paid    Good Loan
7      1008          Ravi           Approved             Paid    Good Loan
8      1009          Neha           Rejected          Default     Rejected
9      1010          Aman           Approved             Paid    Good Loan
10     1011        Suresh           Approved             Paid    Good Loan
11     1012         Divya           Rejected          Default     Rejected
12     1013        Naveen           Approved             Paid    Good Loan
13     1014         Pooja           Approved             Late     Bad Loan
14     1015         Imran           Approved             Paid    Good Loan
15     1016         Kavya           Rejected          Default     Rejected
16     1017         Rohit           Approved             Paid    Good Loan
17     1018         Meena           Rejected          Default     Rejected
18     1019          Adil           Approved             Paid    Good Loan
19     1020        Swathi           Approved             Late     Bad Loan
20     1021         Manoj           Approved             Paid    Good Loan
21     1022        Ayesha           Approved             Paid    Good Loan
22     1023         Tarun           Rejected          Default     Rejected
23     1024       Lakshmi           Rejected          Default     Rejected
24     1025        Farhan           Approved             Paid    Good Loan
25     1026        Deepak           Approved             Paid    Good Loan
26     1027         Nisha           Approved             Paid    Good Loan
27     1028         Varun           Rejected          Default     Rejected
28     1029        Shreya           Approved             Paid    Good Loan
29     1030         Akash           Approved             Paid    Good Loan

In [7]:
# Create time-based columns

df["Application_Year"] = df["Application_Date"].dt.year

df["Application_Month"] = df["Application_Date"].dt.month_name()

df["Application_Month_Number"] = df["Application_Date"].dt.month

df["Year_Month"] = df["Application_Date"].dt.strftime("%Y-%m")

print("Time columns created successfully!")
print()

print(
    df[
        [
            "Loan_ID",
            "Application_Date",
            "Application_Year",
            "Application_Month",
            "Year_Month"
        ]
    ].head(10)
)

Time columns created successfully!

   Loan_ID Application_Date  Application_Year Application_Month Year_Month
0     1001       2025-01-05              2025           January    2025-01
1     1002       2025-01-12              2025           January    2025-01
2     1003       2025-01-20              2025           January    2025-01
3     1004       2025-02-03              2025          February    2025-02
4     1005       2025-02-15              2025          February    2025-02
5     1006       2025-02-25              2025          February    2025-02
6     1007       2025-03-08              2025             March    2025-03
7     1008       2025-03-18              2025             March    2025-03
8     1009       2025-03-28              2025             March    2025-03
9     1010       2025-04-06              2025             April    2025-04

In [8]:
# Bank Loan KPIs

total_applications = len(df)

approved_loans = (df["Application_Status"] == "Approved").sum()

rejected_loans = (df["Application_Status"] == "Rejected").sum()

total_funded_amount = df["Funded_Amount"].sum()

total_received_amount = df["Received_Amount"].sum()

approval_rate = (approved_loans / total_applications) * 100

good_loans = (df["Loan_Quality"] == "Good Loan").sum()

bad_loans = (df["Loan_Quality"] == "Bad Loan").sum()

bad_loan_rate = (bad_loans / approved_loans) * 100


print("BANK LOAN KPI SUMMARY")
print("=====================")

print("Total Applications :", total_applications)
print("Approved Loans     :", approved_loans)
print("Rejected Loans     :", rejected_loans)
print("Total Funded Amount: ₹", total_funded_amount)
print("Total Received Amt : ₹", round(total_received_amount, 2))
print("Approval Rate      :", round(approval_rate, 2), "%")
print("Good Loans         :", good_loans)
print("Bad Loans          :", bad_loans)
print("Bad Loan Rate      :", round(bad_loan_rate, 2), "%")

BANK LOAN KPI SUMMARY
=====================
Total Applications : 30
Approved Loans     : 23
Rejected Loans     : 7
Total Funded Amount: ₹ 12190000
Total Received Amt : ₹ 14209000.0
Approval Rate      : 76.67 %
Good Loans         : 20
Bad Loans          : 3
Bad Loan Rate      : 13.04 %

In [9]:
# Region-wise Loan Analysis

region_analysis = df.groupby("Region").agg(
    Total_Applications=("Loan_ID", "count"),
    Total_Funded_Amount=("Funded_Amount", "sum"),
    Total_Received_Amount=("Received_Amount", "sum"),
    Average_Loan_Amount=("Loan_Amount", "mean")
).reset_index()

print("REGION-WISE LOAN ANALYSIS")
print("=========================")

print(region_analysis)

REGION-WISE LOAN ANALYSIS
=========================
  Region  Total_Applications  Total_Funded_Amount  Total_Received_Amount  \
0   East                   5              1420000              2030000.0
1  North                   6              3370000              3707000.0
2  South                  13              5120000              5828000.0
3   West                   6              2280000              2644000.0

   Average_Loan_Amount
0        518000.000000
1        561666.666667
2        459230.769231
3        468333.333333

In [10]:
# Customer-wise Loan Analysis

customer_analysis = df[
    [
        "Customer_Name",
        "Loan_ID",
        "Loan_Amount",
        "Funded_Amount",
        "Received_Amount",
        "Application_Status",
        "Repayment_Status",
        "Loan_Quality"
    ]
].sort_values("Loan_Amount", ascending=False)

print("CUSTOMER-WISE LOAN ANALYSIS")
print("===========================")

print(customer_analysis)

CUSTOMER-WISE LOAN ANALYSIS
===========================
   Customer_Name  Loan_ID  Loan_Amount  Funded_Amount  Received_Amount  \
22         Tarun     1023       950000              0         380000.0
7           Ravi     1008       900000         900000         990000.0
16         Rohit     1017       800000         800000         880000.0
3          Kiran     1004       750000         750000         825000.0
26         Nisha     1027       720000         720000         792000.0
12        Naveen     1013       700000         700000         770000.0
29         Akash     1030       680000         680000         748000.0
14         Imran     1015       650000         650000         715000.0
24        Farhan     1025       620000         620000         682000.0
6          Sneha     1007       600000         600000         660000.0
21        Ayesha     1022       580000         580000         638000.0
10        Suresh     1011       550000         550000         605000.0
18          Adil     1019       500000         500000         550000.0
2          Priya     1003       500000         500000         550000.0
28        Shreya     1029       470000         470000         517000.0
9           Aman     1010       450000         450000         495000.0
19        Swathi     1020       420000         420000         378000.0
5         Vikram     1006       400000         400000         440000.0
13         Pooja     1014       380000         380000         342000.0
20         Manoj     1021       360000         360000         396000.0
1          Rahul     1002       350000         350000         385000.0
17         Meena     1018       320000              0         128000.0
25        Deepak     1026       310000         310000         341000.0
4         Anjali     1005       300000         300000         270000.0
27         Varun     1028       290000              0         116000.0
11         Divya     1012       280000              0         112000.0
8           Neha     1009       250000              0         100000.0
23       Lakshmi     1024       240000              0          96000.0
15         Kavya     1016       220000              0          88000.0
0         Arshad     1001       200000         200000         220000.0

   Application_Status Repayment_Status Loan_Quality
22           Rejected          Default     Rejected
7            Approved             Paid    Good Loan
16           Approved             Paid    Good Loan
3            Approved             Paid    Good Loan
26           Approved             Paid    Good Loan
12           Approved             Paid    Good Loan
29           Approved             Paid    Good Loan
14           Approved             Paid    Good Loan
24           Approved             Paid    Good Loan
6            Approved             Paid    Good Loan
21           Approved             Paid    Good Loan
10           Approved             Paid    Good Loan
18           Approved             Paid    Good Loan
2            Approved             Paid    Good Loan
28           Approved             Paid    Good Loan
9            Approved             Paid    Good Loan
19           Approved             Late     Bad Loan
5            Approved             Paid    Good Loan
13           Approved             Late     Bad Loan
20           Approved             Paid    Good Loan
1            Approved             Paid    Good Loan
17           Rejected          Default     Rejected
25           Approved             Paid    Good Loan
4            Approved             Late     Bad Loan
27           Rejected          Default     Rejected
11           Rejected          Default     Rejected
8            Rejected          Default     Rejected
23           Rejected          Default     Rejected
15           Rejected          Default     Rejected
0            Approved             Paid    Good Loan

In [11]:
# Approval Factor Analysis

approval_analysis = df.groupby("Application_Status").agg(
    Average_Credit_Score=("Credit_Score", "mean"),
    Average_DTI_Ratio=("DTI_Ratio", "mean"),
    Average_Annual_Income=("Annual_Income", "mean"),
    Average_Loan_Amount=("Loan_Amount", "mean"),
    Number_of_Applications=("Loan_ID", "count")
).reset_index()

print("APPROVAL FACTOR ANALYSIS")
print("========================")

print(approval_analysis.round(2))

APPROVAL FACTOR ANALYSIS
========================
  Application_Status  Average_Credit_Score  Average_DTI_Ratio  \
0           Approved                756.52              21.57
1           Rejected                632.14              43.00

   Average_Annual_Income  Average_Loan_Amount  Number_of_Applications
0              776956.52            530000.00                      23
1              604285.71            364285.71                       7

In [12]:
# Repayment Factor Analysis

repayment_analysis = df.groupby("Repayment_Status").agg(
    Number_of_Loans=("Loan_ID", "count"),
    Average_Credit_Score=("Credit_Score", "mean"),
    Average_DTI_Ratio=("DTI_Ratio", "mean"),
    Average_Annual_Income=("Annual_Income", "mean"),
    Average_Loan_Amount=("Loan_Amount", "mean"),
    Total_Funded_Amount=("Funded_Amount", "sum"),
    Total_Received_Amount=("Received_Amount", "sum")
).reset_index()

print("REPAYMENT FACTOR ANALYSIS")
print("=========================")
# Repayment Factor Analysis

repayment_analysis = df.groupby("Repayment_Status").agg(
    Number_of_Loans=("Loan_ID", "count"),
    Average_Credit_Score=("Credit_Score", "mean"),
    Average_DTI_Ratio=("DTI_Ratio", "mean"),
    Average_Annual_Income=("Annual_Income", "mean"),
    Average_Loan_Amount=("Loan_Amount", "mean"),
    Total_Funded_Amount=("Funded_Amount", "sum"),
    Total_Received_Amount=("Received_Amount", "sum")
).reset_index()

print("REPAYMENT FACTOR ANALYSIS")
print("=========================")

print(repayment_analysis.round(2))
print(repayment_analysis.round(2))

REPAYMENT FACTOR ANALYSIS
=========================
  Repayment_Status  Number_of_Loans  Average_Credit_Score  Average_DTI_Ratio  \
0          Default                7                632.14              43.00
1             Late                3                683.33              32.67
2             Paid               20                767.50              19.90

   Average_Annual_Income  Average_Loan_Amount  Total_Funded_Amount  \
0              604285.71            364285.71                    0
1              620000.00            366666.67              1100000
2              800500.00            554500.00             11090000

   Total_Received_Amount
0              1020000.0
1               990000.0
2             12199000.0

In [13]:
# Final dataset check

print("FINAL BANK LOAN DATASET")
print("=======================")

print("Rows    :", df.shape[0])
print("Columns :", df.shape[1])

print("\nAll Columns:")
print(df.columns.tolist())

print("\nFirst 10 Records:")
display(df.head(10))

FINAL BANK LOAN DATASET
=======================
Rows    : 30
Columns : 23

All Columns:
['Loan_ID', 'Customer_Name', 'Age', 'Gender', 'Region', 'Employment_Type', 'Annual_Income', 'Loan_Amount', 'Interest_Rate', 'Loan_Term_Years', 'Credit_Score', 'DTI_Ratio', 'Loan_Purpose', 'Application_Status', 'Repayment_Status', 'Application_Date', 'Funded_Amount', 'Received_Amount', 'Loan_Quality', 'Application_Year', 'Application_Month', 'Application_Month_Number', 'Year_Month']

First 10 Records:

,Loan_ID,Customer_Name,Age,Gender,Region,Employment_Type,Annual_Income,Loan_Amount,Interest_Rate,Loan_Term_Years,...,Application_Status,Repayment_Status,Application_Date,Funded_Amount,Received_Amount,Loan_Quality,Application_Year,Application_Month,Application_Month_Number,Year_Month
0,1001,Arshad,24,Male,South,Salaried,450000,200000,8.5,5,...,Approved,Paid,2025-01-05,200000,220000.0,Good Loan,2025,January,1,2025-01
1,1002,Rahul,29,Male,South,Self-Employed,650000,350000,9.2,7,...,Approved,Paid,2025-01-12,350000,385000.0,Good Loan,2025,January,1,2025-01
2,1003,Priya,35,Female,West,Salaried,800000,500000,7.8,10,...,Approved,Paid,2025-01-20,500000,550000.0,Good Loan,2025,January,1,2025-01
3,1004,Kiran,42,Male,North,Salaried,950000,750000,8.1,15,...,Approved,Paid,2025-02-03,750000,825000.0,Good Loan,2025,February,2,2025-02
4,1005,Anjali,31,Female,South,Self-Employed,550000,300000,10.5,5,...,Approved,Late,2025-02-15,300000,270000.0,Bad Loan,2025,February,2,2025-02
5,1006,Vikram,27,Male,East,Salaried,720000,400000,9.0,7,...,Approved,Paid,2025-02-25,400000,440000.0,Good Loan,2025,February,2,2025-02
6,1007,Sneha,39,Female,South,Salaried,880000,600000,8.2,10,...,Approved,Paid,2025-03-08,600000,660000.0,Good Loan,2025,March,3,2025-03
7,1008,Ravi,45,Male,West,Self-Employed,1100000,900000,7.5,15,...,Approved,Paid,2025-03-18,900000,990000.0,Good Loan,2025,March,3,2025-03
8,1009,Neha,26,Female,South,Salaried,480000,250000,11.0,5,...,Rejected,Default,2025-03-28,0,100000.0,Rejected,2025,March,3,2025-03
9,1010,Aman,33,Male,North,Salaried,600000,450000,9.5,7,...,Approved,Paid,2025-04-06,450000,495000.0,Good Loan,2025,April,4,2025-04

In [6]:

!pip install pandas plotly ipywidgets

Requirement already satisfied: pandas in .\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: plotly in .\anaconda3\Lib\site-packages (6.7.0)
Requirement already satisfied: ipywidgets in .\anaconda3\Lib\site-packages (8.1.7)
Requirement already satisfied: numpy>=2.3.3 in .\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: narwhals>=1.15.1 in .\anaconda3\Lib\site-packages (from plotly) (2.23.0)
Requirement already satisfied: packaging in .\anaconda3\Lib\site-packages (from plotly) (26.0)
Requirement already satisfied: comm>=0.1.3 in .\anaconda3\Lib\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in .\anaconda3\Lib\site-packages (from ipywidgets) (9.15.0)
Requirement already satisfied: traitlets>=4.3.1 in .\anaconda3\Lib\site-packages (from ipywidgets) (5.15.0)
Requirement already satisfied: widgetsnbextension~=4.0.14 in .\anaconda3\Lib\site-packages (from ipywidgets) (4.0.14)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in .\anaconda3\Lib\site-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: colorama>=0.4.4 in .\anaconda3\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in .\anaconda3\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in .\anaconda3\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in .\anaconda3\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.6 in .\anaconda3\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in .\anaconda3\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: psutil>=7 in .\anaconda3\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in .\anaconda3\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in .\anaconda3\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in .\anaconda3\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.8.2)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in .\anaconda3\Lib\site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets) (0.8.7)
Requirement already satisfied: six>=1.5 in .\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in .\anaconda3\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in .\anaconda3\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure_eval in .\anaconda3\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)

In [7]:

import pandas as pd

df = pd.read_csv("Bank_Loan_Analysis_Dataset.csv")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

display(df.head())

Dataset loaded successfully!
Rows: 30
Columns: 23

,Loan_ID,Customer_Name,Age,Gender,Region,Employment_Type,Annual_Income,Loan_Amount,Interest_Rate,Loan_Term_Years,...,Application_Status,Repayment_Status,Application_Date,Funded_Amount,Received_Amount,Loan_Quality,Application_Year,Application_Month,Application_Month_Number,Year_Month
0,1001,Arshad,24,Male,South,Salaried,450000,200000,8.5,5,...,Approved,Paid,2025-01-05,200000,220000.0,Good Loan,2025,January,1,2025-01
1,1002,Rahul,29,Male,South,Self-Employed,650000,350000,9.2,7,...,Approved,Paid,2025-01-12,350000,385000.0,Good Loan,2025,January,1,2025-01
2,1003,Priya,35,Female,West,Salaried,800000,500000,7.8,10,...,Approved,Paid,2025-01-20,500000,550000.0,Good Loan,2025,January,1,2025-01
3,1004,Kiran,42,Male,North,Salaried,950000,750000,8.1,15,...,Approved,Paid,2025-02-03,750000,825000.0,Good Loan,2025,February,2,2025-02
4,1005,Anjali,31,Female,South,Self-Employed,550000,300000,10.5,5,...,Approved,Late,2025-02-15,300000,270000.0,Bad Loan,2025,February,2,2025-02

In [8]:

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

# ---------------- PREPARE DATA ----------------
df = df.copy()
df.columns = df.columns.str.strip()

required = [
    "Loan_ID", "Region", "Application_Status", "Repayment_Status",
    "Application_Date", "Funded_Amount", "Received_Amount",
    "Loan_Quality", "Application_Year", "Employment_Type",
    "Interest_Rate", "Annual_Income", "Loan_Amount"
]

missing = [c for c in required if c not in df.columns]
if missing:
    raise ValueError(f"Missing columns: {missing}")

for c in [
    "Funded_Amount", "Received_Amount", "Loan_Amount",
    "Annual_Income", "Interest_Rate"
]:
    df[c] = pd.to_numeric(df[c], errors="coerce")

df["Application_Date"] = pd.to_datetime(
    df["Application_Date"], errors="coerce"
)

# ---------------- SIMPLE THEME ----------------
BG = "#F5F6F7"
TEXT = "#30343B"
MUTED = "#737982"
BORDER = "#E0E3E7"
BLUE = "#6F8FA8"
GREEN = "#7D9887"
RED = "#B98484"
GREY = "#A7ADB4"

display(HTML(f"""
<style>
.jp-OutputArea-output {{ background-color: {BG}; }}
</style>
<div style="background:white;color:{TEXT};padding:22px 25px;
border-bottom:2px solid {BORDER};font-family:Arial">
  <div style="font-size:11px;letter-spacing:1.5px;color:{MUTED}">
    FINANCIAL PERFORMANCE REPORT
  </div>
  <h1 style="margin:8px 0;font-size:27px;font-weight:600">
    BANK LOAN ANALYSIS
  </h1>
  <p style="margin:0;color:{MUTED}">
    Loan Applications | Funding | Repayment | Credit Risk
  </p>
</div>
"""))

# ---------------- FILTERS ----------------
def get_options(col):
    return ["All"] + sorted(df[col].dropna().astype(str).unique().tolist())

region_filter = widgets.Dropdown(
    options=get_options("Region"),
    description="Region:",
    layout=widgets.Layout(width="220px")
)

year_filter = widgets.Dropdown(
    options=["All"] + sorted(
        df["Application_Year"].dropna().astype(str).unique().tolist()
    ),
    description="Year:",
    layout=widgets.Layout(width="200px")
)

quality_filter = widgets.Dropdown(
    options=get_options("Loan_Quality"),
    description="Loan Quality:",
    layout=widgets.Layout(width="260px")
)

output = widgets.Output()

# ---------------- KPI CARD ----------------
def make_card(label, value, accent):
    return f"""
    <div style="background:white;padding:17px 19px;
    border:1px solid {BORDER};border-top:3px solid {accent};
    border-radius:5px;flex:1;min-width:135px;font-family:Arial">
      <div style="font-size:11px;color:{MUTED};font-weight:500">
        {label}
      </div>
      <div style="font-size:23px;color:{TEXT};
      font-weight:600;margin-top:10px">{value}</div>
    </div>
    """

# ---------------- CHART STYLE ----------------
def style_chart(fig):
    fig.update_layout(
        template="plotly_white",
        paper_bgcolor="white",
        plot_bgcolor="white",
        font=dict(family="Arial", color=TEXT, size=12),
        title_font=dict(size=16, color=TEXT),
        margin=dict(l=35, r=25, t=65, b=40),
        colorway=[BLUE, GREEN, GREY, RED],
        legend=dict(
            orientation="h", yanchor="bottom", y=1.02,
            xanchor="right", x=1
        )
    )
    fig.update_xaxes(showgrid=False, linecolor=BORDER)
    fig.update_yaxes(gridcolor="#ECEEF0", zeroline=False)
    return fig

def show_chart(fig):
    fig = style_chart(fig)
    fig.show()

# ---------------- BUILD DASHBOARD ----------------
def update_dashboard(change=None):
    data = df.copy()

    if region_filter.value != "All":
        data = data[data["Region"].astype(str) == region_filter.value]

    if year_filter.value != "All":
        data = data[
            data["Application_Year"].astype(str) == year_filter.value
        ]

    if quality_filter.value != "All":
        data = data[
            data["Loan_Quality"].astype(str) == quality_filter.value
        ]

    with output:
        clear_output(wait=True)

        if data.empty:
            print("No records match the selected filters.")
            return

        total = len(data)
        funded = data["Funded_Amount"].sum()
        received = data["Received_Amount"].sum()
        approved = data["Application_Status"].astype(str).str.lower().eq("approved").sum()
        good = data["Loan_Quality"].astype(str).str.lower().eq("good loan").sum()
        bad = data["Loan_Quality"].astype(str).str.lower().eq("bad loan").sum()

        # KPI row
        kpis = [
            ("TOTAL APPLICATIONS", f"{total:,}", BLUE),
            ("FUNDED AMOUNT", f"₹{funded:,.0f}", GREY),
            ("AMOUNT RECEIVED", f"₹{received:,.0f}", GREEN),
            ("APPROVAL RATE", f"{approved/total:.1%}", BLUE),
            ("GOOD LOANS", f"{good:,}", GREEN),
            ("BAD LOANS", f"{bad:,}", RED)
        ]

        display(HTML(
            '<div style="display:flex;flex-wrap:wrap;gap:12px;margin:14px 0 24px">'
            + "".join(make_card(*item) for item in kpis)
            + "</div>"
        ))

        # Good vs bad loans
        quality = data["Loan_Quality"].value_counts().reset_index()
        quality.columns = ["Loan Quality", "Applications"]

        fig = px.pie(
            quality, names="Loan Quality", values="Applications",
            title="Loan Quality Distribution", hole=0.55,
            color_discrete_sequence=[GREEN, RED, GREY]
        )
        fig.update_traces(textposition="inside", textinfo="percent+label")
        show_chart(fig)

        # Application status
        status = data["Application_Status"].value_counts().reset_index()
        status.columns = ["Application Status", "Applications"]

        fig = px.bar(
            status, x="Application Status", y="Applications",
            title="Applications by Status", text="Applications",
            color_discrete_sequence=[BLUE]
        )
        show_chart(fig)

        # Monthly trends
        dated = data.dropna(subset=["Application_Date"]).copy()

        if not dated.empty:
            dated["Month"] = dated["Application_Date"].dt.to_period("M").astype(str)

            monthly = dated.groupby("Month", as_index=False).agg(
                Applications=("Loan_ID", "count"),
                Funded=("Funded_Amount", "sum"),
                Received=("Received_Amount", "sum")
            )

            fig = px.line(
                monthly, x="Month", y="Applications",
                title="Monthly Loan Applications", markers=True,
                color_discrete_sequence=[BLUE]
            )
            show_chart(fig)

            fig = go.Figure()
            fig.add_trace(go.Scatter(
                x=monthly["Month"], y=monthly["Funded"],
                name="Funded Amount", mode="lines+markers",
                line=dict(color=BLUE, width=2)
            ))
            fig.add_trace(go.Scatter(
                x=monthly["Month"], y=monthly["Received"],
                name="Received Amount", mode="lines+markers",
                line=dict(color=GREEN, width=2)
            ))
            fig.update_layout(title="Funded Amount vs Amount Received")
            show_chart(fig)

        # Regional performance
        regional = data.groupby("Region", as_index=False).agg(
            Applications=("Loan_ID", "count"),
            Funded=("Funded_Amount", "sum")
        ).sort_values("Funded", ascending=False)

        fig = px.bar(
            regional, x="Region", y="Funded",
            title="Funded Amount by Region",
            color_discrete_sequence=[BLUE]
        )
        show_chart(fig)

        # Repayment status
        repayment = data["Repayment_Status"].value_counts().reset_index()
        repayment.columns = ["Repayment Status", "Applications"]

        fig = px.bar(
            repayment, x="Repayment Status", y="Applications",
            title="Repayment Status Analysis", text="Applications",
            color_discrete_sequence=[GREEN]
        )
        show_chart(fig)

        # Employment and loan quality
        employment = data.groupby(
            ["Employment_Type", "Loan_Quality"]
        ).size().reset_index(name="Applications")

        fig = px.bar(
            employment, x="Employment_Type", y="Applications",
            color="Loan_Quality", barmode="group",
            title="Loan Quality by Employment Type",
            color_discrete_map={
                "Good Loan": GREEN,
                "Bad Loan": RED,
                "Rejected": GREY
            }
        )
        show_chart(fig)

        # Interest rate and loan quality
        fig = px.box(
            data, x="Loan_Quality", y="Interest_Rate",
            title="Interest Rate by Loan Quality",
            color_discrete_sequence=[BLUE]
        )
        show_chart(fig)

        # Income vs loan amount
        fig = px.scatter(
            data, x="Annual_Income", y="Loan_Amount",
            title="Annual Income vs Loan Amount",
            color="Loan_Quality",
            color_discrete_map={
                "Good Loan": GREEN,
                "Bad Loan": RED,
                "Rejected": GREY
            }
        )
        show_chart(fig)

        # Summary
        display(HTML(f"""
        <div style="margin-top:15px;padding:18px;background:white;
        border:1px solid {BORDER};border-radius:5px;
        font-family:Arial;color:{TEXT}">
          <b>REPORT SUMMARY</b><br><br>
          Applications analyzed: {total:,}<br>
          Approved applications: {approved:,}<br>
          Total funded: ₹{funded:,.2f}<br>
          Total received: ₹{received:,.2f}
        </div>
        """))

region_filter.observe(update_dashboard, names="value")
year_filter.observe(update_dashboard, names="value")
quality_filter.observe(update_dashboard, names="value")

display(widgets.HBox(
    [region_filter, year_filter, quality_filter],
    layout=widgets.Layout(gap="12px", margin="15px 0")
))
display(output)

update_dashboard()

HBox(children=(Dropdown(description='Region:', layout=Layout(width='220px'), options=('All', 'East', 'North', …

Output()